### ISSUE TITLE
Please submit a package deletion request on pub-dev

### ISSUE THREAD

**Issue by miyoyo** [hardyeats/davison#1]
Hello,

I am an user concerned with the health of https://pub.dev, and it seems that your package is *explicitly* not intended to be on pub. As you acknowledge this in your description, I've come to ask you to please file a formal pub deletion request at https://github.com/dart-lang/pub-dev/issues

Thank you for keeping pub clean.

**Comment by hardyeats** [comment]
https://github.com/dart-lang/pub-dev/issues/2746

sorry about your inconvenience.

**Comment by miyoyo** [comment]
If you want to use your package in your projects, you can use less-known features of the pubspec file, such as [directly pointing to this repository](https://dart.dev/tools/pub/dependencies#git-packages) or using [a copy of it in a folder](https://dart.dev/tools/pub/dependencies#path-packages)

Thanks again for keeping pub clean!
